# Generated by Django 5.1.7 on 2025-03-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out'), ('MISSING_PUNCH', 'Missing Punch')], default='CHECK_IN', max_length=20),
        ),
    ]
